
title: "👨‍💻 Ivan Maslov . Иван Маслов"
description: Senior Developer at Ridestore.com | Contacts and information
baseurl: "" 
blogurl: "/blog"
url: "https://studentivan.ru"

host: 0.0.0.0
port: 4000

disqus:
  shortname: studentivan

# Contacts

public_profiles:
  - title: twitter
    username: IvanTranquility
    url: https://twitter.com/
    color: "#00aced"
  - title: instagram
    username: studentivan
    url: http://instagram.com/
    visible: false
    color: "#517fa4"
  - title: github
    username: studentIvan
    url: https://github.com/
    color: "#a8a8a8"
  - title: habrahabr
    username: student_ivan
    url: https://habrahabr.ru/users/
    icon: header
    color: "#8baab5"
  - title: vk.com
    username: dr.tranquility
    url: https://vk.com/
    icon: vk
    color: "#45668e"
  - title: facebook
    username: ivan.tranquility
    url: https://www.facebook.com/
    color: "#3b5998"

skype_username:  radio.coder  # skype:radio.coder?call
facetime_number:  "79992284007"  # facetime:79995643839
phone_number:  "+79992284007"  # tel:+79995643839
phone_number_pretty:  "+7 (999) 228-4-007"
email: mail@studentivan.ru
email_hash: d58e6abd5a8c6a45366797e28d6bdf21

pgp_public_key: "E69E1D98.asc"

# Build settings
markdown: kramdown
theme: minima
timezone: Europe/Moscow
# highlighter: pygments 

menu:
  - home
  - portfolio
  - resume

defaults:
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"